package com.fullcontact.apilib.models.enums;

public enum FCApiEndpoint {
  PERSON_ENRICH,
  COMPANY_ENRICH,
  IDENTITY_MAP,
  IDENTITY_RESOLVE,
  IDENTITY_RESOLVE_WITH_TAGS,
  IDENTITY_DELETE,
  IDENTITY_MAP_RESOLVE,
  TAGS_CREATE,
  TAGS_GET,
  TAGS_DELETE,
  AUDIENCE_CREATE,
  AUDIENCE_DOWNLOAD,
  PERMISSION_CREATE,
  PERMISSION_DELETE,
  PERMISSION_FIND,
  PERMISSION_CURRENT,
  PERMISSION_VERIFY
}
