package com.fullcontact.apilib.models.enums;

public enum FCApiEndpoint {
  PERSON_ENRICH,
  COMPANY_ENRICH,
  COMPANY_SEARCH,
  IDENTITY_MAP,
  IDENTITY_RESOLVE,
  IDENTITY_RESOLVE_WITH_TAGS,
  IDENTITY_DELETE,
  EMAIL_VERIFICATION
}
